name: "run playwright tests"
description: "run playwright tests"

inputs:
  category:
    required: true
runs:
  steps:
    - name: Run your tests
      shell: bash
      run: |
        pushd 'Playwright'
        dotnet test --configuration Release \
          --no-restore \
          --results-directory TestResults\${{ inputs.category }} \
          --logger "trx" \
          --collect:"XPlat Code Coverage;Format=cobertura" \
          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByAttribute="Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute" \
          -- RunConfiguration.TreatNoTestsAsError=true \
          --filter TestCategory=${{ inputs.category }}
          tests/**/*.csproj
        popd
    - uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: 🎁 Test Results
        path: './Playwright/TestResults/${{ inputs.category }}/*.trx'
        reporter: dotnet-trx
        fail-on-error: false       
   